- name: config replication on l1 replicas
  shell: 
    cmd: "{{ scripts_dir }}/get_replica_from_{{my_master}}.sh"
    warn: false
  when: not master and hostvars[my_master]['master']

- name: config replication on l2 replicas
  shell: 
    cmd: "{{ scripts_dir }}/get_replica_from_{{my_master}}.sh"
    warn: false
  when: not master and not hostvars[my_master]['master']
