- name: "Install repository package"
  yum: 
    state: present
    pkg: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ (ansible_distribution_version | splitext)[0] }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
  environment: "{{ proxy_env }}"
  
- name: install PostgreSQL
  yum:
    name: postgresql{{ ver }}-server
  environment: "{{ proxy_env }}"

- name: install PostgreSQL-contrib
  yum:
    name: postgresql{{ ver }}-contrib
  environment: "{{ proxy_env }}"
  tags: 
    - reconfigure

- name: install psycopg2
  yum:
    name: python-psycopg2
  environment: "{{ proxy_env }}"

- name: disable build-in module for centos 8
  shell: dnf -qy module disable postgresql
  when: ansible_distribution == 'CentOS' and (ansible_distribution_version | splitext)[0] == '8'

- name: init db
  shell: if [ ! -f {{ pgdata }}/PG_VERSION ]; then /usr/pgsql-{{ ver }}/bin/postgresql-{{ ver }}-setup initdb; fi

- name: Enable end start PostgreSQL service
  systemd:
    name: postgresql-{{ ver }}
    state: started
    enabled: yes
  
- name: Template configuration file to postgresql.conf
  template:
    src: postgresql.conf.j2
    dest: '{{ pgdata }}/postgresql.conf'
  notify:
    - restart pgsql
  tags: reconfigure
  

- name: Template configuration file to pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: '{{ pgdata }}/pg_hba.conf'
  notify:
    - restart pgsql
  tags: reconfigure   

- name: Open ports for pgsql
  firewalld:
    port: "5432/tcp"
    permanent: yes
    state: enabled
    immediate: yes

- name: Restart PostgreSQL service
  systemd:
    name: postgresql-{{ ver }}
    state: restarted
  tags: reconfigure
  
- name: set password for postgres
  postgresql_user:
    db: postgres
    user: postgres
    password: '{{ pgpassword }}'
  no_log: False  
  become_user: postgres
  become: yes
  tags: reconfigure

- name: set password for postgres
  postgresql_user:
    db: postgres
    user: repuser
    password: '{{ reppassword }}'
    role_attr_flags: REPLICATION
  become_user: postgres
  become: yes
  tags: reconfigure

- name: Stop PostgreSQL service on replica
  systemd:
    name: postgresql-{{ ver }}
    state: stopped
  
  
