
- name: firewall - open ports 
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - 9092
    - 2181
    - 9001
    - 80

- name: firewall - open vrrp proto
  firewalld:
    rich_rule: 'rule protocol value="vrrp" accept'
    permanent: yes
    state: enabled
    immediate: yes

- name: install soft
  yum:
    name: "{{ packages }}"
  environment: "{{ proxy_env }}"
  vars:
    packages:
    - keepalived
    - haproxy

- name: Set haproxy_connect_any flag on and keep it persistent across reboots
  shell: "setsebool -P haproxy_connect_any 1"
    
- name: Template configuration file to keepalived.conf
  template:
    src: keepalived.conf.j2
    dest: '/etc/keepalived/keepalived.conf'
  notify:
    - restart keepalived.service

- name: Template configuration file to haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: '/etc/haproxy/haproxy.cfg'
  notify:
    - restart haproxy.service  


- name: enable and start keepalived.service
  systemd:
    name: keepalived
    state: started
    enabled: yes


- name: enable and start haproxy.service
  systemd:
    name: haproxy
    state: started
    enabled: yes