
- name: restart zookeeper service 
  systemd:
    state: restarted
    daemon_reload: yes
    name: zookeeper
    
- name: restart kafka service 
  systemd:
    state: restarted
    daemon_reload: yes
    name: kafka
  