---
- name: get kafka and zookeeper status
  block: 
  - name: get service facts
    service_facts:

  - name: zookeeper status
    debug:
        var: ansible_facts.services["zookeeper.service"]["state"]

  - name: kafka status
    debug:
        var: ansible_facts.services["kafka.service"]["state"]
  tags:
    - never
    - status

- name: Clean kafka dirs
  include_tasks: clean.yml
  tags:
    - never
    - clean

- name: Clean kafka data dirs
  include_tasks: clean-data.yml
  tags:
    - never
    - clean-data

- name: Restart kafka and zookeeper services
  systemd:
    state: restarted
    daemon_reload: yes
    name: "{{ item }}"
  with_items:
    - zookeeper
    - kafka
  tags:  
    - never
    - restart

#- name: test pervius installation
#  include_tasks: is_isnstalled.yml

- name: install java
  yum:
    name: "{{ packages }}"
  environment: "{{ proxy_env }}"
  vars:
    packages:
    - java-1.8.0-openjdk 
    - java-1.8.0-openjdk-devel

- name: Create kafka group
  group:
    name: '{{ kafka_group }}'
    state: present

- name: Create kafka user
  user:
    name: '{{ kafka_user }}'
    group: '{{ kafka_group }}'
    state: present
    createhome: yes

- name: install zookeeper
  include_tasks: zoo.yml
  tags:
    - reconfigure
  
- name: install kafka
  include_tasks: kafka.yml
  tags:
    - reconfigure
    - change
    
- name: Create a scripts directory if it does not exist
  file:
    path: '{{ scripts_dir }}'
    state: directory
    mode: '0771'

- name: create scripts
  template:
    src: '{{ item }}'
    dest: /{{ scripts_dir }}/{{ item | basename | regex_replace('\.j2','') }}
    mode: '0755'
  with_fileglob:
    - templates/scripts/*.j2
  tags:
    - reconfigure

- name: install python3
  yum:
    name: python3
  environment: "{{ proxy_env }}"
  tags:
    - reconfigure

- name: install pip3
  yum:
    name: python3-pip
  environment: "{{ proxy_env }}"
  tags:
    - reconfigure

- name: install pyyaml
  shell: pip3 install pyyaml
  environment: "{{ proxy_env }}"
  tags:
    - reconfigure

- name: Copy config_topics.py
  copy:
    src: config_topics.py
    dest: "{{ scripts_dir }}/config_topics.py"

- name: restart service zookeeper
  systemd:
    state: restarted
    daemon_reload: yes
    name: zookeeper
  tags:
    - restart
    - never
  throttle: 1

- name: restart service kafka
  systemd:
    state: restarted
    daemon_reload: yes
    name: kafka
  tags:
    - restart
    - never
  throttle: 1

- name: add user {{ user_name }} with password
  become: true
  user:
    name: "{{ user_name }}"
    groups: "kafka"
    shell: /bin/bash
    password: "{{ user_pass | string | password_hash('sha512') }}"
    append: yes
    update_password: on_create
