- name: install PostgreSQL
  include_tasks: install_pg.yml
  tags:
    - repl
- name: Stop PostgreSQL service
  systemd:
    name: postgresql-{{ ver }}
    state: stopped
  tags:
    - clean
    - never

- name: Clean pg data
  shell: yum -y remove postgres\*; rm -rf /var/lib/pgsql/12/data/*; rm -rf /usr/pgsql-12; 
  tags: 
    - clean
    - never
