- name: install PostgreSQL
  include_tasks: install_pg.yml
  tags:
    - repl
    - reconfigure

- name: backup PostgreSQL
  include_tasks: backuping_pg.yml
  tags:
    - backup
    #- reconfigure
    - never



- name: restore PostgreSQL backup 
  include_tasks: restore_pg.yml
  tags:
    - restore
    #- reconfigure
    - never

- name: set timezone to Europe/Kiev
  timezone:
    name: Europe/Kiev

- name: Stop PostgreSQL service
  systemd:
    name: postgresql-{{ ver }}
    state: stopped
  tags:
    - clean
    - never

- name: Clean pg data
  shell: yum -y remove postgres\*; rm -rf /var/lib/pgsql/12/data/*; rm -rf /usr/pgsql-12; 
  tags: 
    - clean
    - never
