---
- name: Upgrade system
  yum:
    name: "*"
    state: latest
  environment: "{{ proxy_env }}"


- name: install basic soft
  yum:
    name: "{{ packages }}"
  environment: "{{ proxy_env }}"
  vars:
    packages:
    - git
    - htop
    - iotop
    - nmap
    - mc
    - tcpdump
    - wget
    - nano
    - atop
    - net-tools
    - git
    - tig
    - jq
    - curl
    - yum-utils
    - bind-utils
    - mlocate
